Controllers/FileDownloaderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;

namespace RecruitmentSystemWebApplication.Controllers
{

    /// <summary>
    /// Class <c>FileDownloaderController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required when a file is to be sent to the client web browser for download. Images displayed in a view do not use
    /// this controller class, nor its action methods.
    /// </summary>
    public class FileDownloaderController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public FileDownloaderController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Controller Action Method <c>DownloadCVFile</c> calls the Application Logic responsible of retrieving the file bytes array
        /// of a CV File by the JobApplicationID and returns the file to the client web browser for download.
        /// </summary>
        [HttpPost]
        public FileResult DownloadCVFile(int JobApplicationID)
        {
            JobApplicationApplicationLogic jobApplicationApplicationObject = new JobApplicationApplicationLogic();
            Byte[] CVFileBytes = jobApplicationApplicationObject.GetCVFileBytesArrayByJobApplicationID(JobApplicationID);

            // Return a PDF File using the retrieved CVFileBytes & Multipurpose Internet Mail Extensions (MIME) PDF Type to the client
            // web browser for download.
            // Reference for MIME types: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
            return File(CVFileBytes, "application/pdf");
        }
    }
}

Controllers/JobApplicationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;
using RecruitmentSystemWebApplication.DataAccessLayer.DropDownLists;
using RecruitmentSystemWebApplication.Models;

namespace RecruitmentSystemWebApplication.Controllers
{
    /// <summary>
    /// Class <c>JobApplicationController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for Job Application functionalities.
    /// </summary>
    public class JobApplicationController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public JobApplicationController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Class <c>CreateJobApplication</c> is the controller action method which gets the details of a job vacancy and returns the
        /// CreateJobApplication View. It uses the JobApplicationApplicationLogic class to retrive the Job Vacancy Details.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> CreateJobApplication(int JobVacancyID)
        {
            JobApplicationModel jobApplicationModelObject = new JobApplicationModel();
            jobApplicationModelObject.JobVacancyID = JobVacancyID;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobApplicationModelObject.JobseekerUsername = user.UserName;

            // Get Job Vacancy Details using the Application Logic Layer.
            JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
            jobApplicationModelObject = jobApplicationApplicationLogicObject.GetJobVacancyDetailsByJobVacancyID(jobApplicationModelObject);

            // Populate the View's Dropdown Menu/ Select lists
            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobApplicationModelObject.YearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobApplicationModelObject.AcademicEducationQualificationLevelList =
                requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

            SalaryRange salaryRange = new SalaryRange();
            jobApplicationModelObject.SalaryRangeList = salaryRange.GetSalaryRangeList();

            return View(jobApplicationModelObject);
        }

        /// <summary>
        /// Controller Action Post Method <c>CreateJobApplication</c> is the action method which responsible of creating the job application
        /// after the user submits the Create Job Applicaiton form from the respective view.
        /// It uses the JobApplicationApplicationLogic class to create the Job Application.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CreateJobApplication(JobApplicationModel jobApplicationModelObject)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobApplicationModelObject.JobseekerUsername = user.UserName;

            // If server-side validation passes, call the Application Logic Layer to create the Job Application.
            if (ModelState.IsValid)
            {
                // Create Job Application
                JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
                jobApplicationModelObject = jobApplicationApplicationLogicObject.CreateJobApplicationApplicationLogic(jobApplicationModelObject);

                // Populate Job Application Model Object with related Job Vacancy Details
                jobApplicationModelObject = jobApplicationApplicationLogicObject.GetJobVacancyDetailsByJobVacancyID(jobApplicationModelObject);

                // Populate Dropdown lists
                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobApplicationModelObject.YearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobApplicationModelObject.AcademicEducationQualificationLevelList =
                    requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobApplicationModelObject.SalaryRangeList = salaryRange.GetSalaryRangeList();

                Console.WriteLine("Job Application created");

                // return View with the Job Application Model Object
                return View(jobApplicationModelObject);
            }

            // Else (hence server-side validation on the model object does not pass), get the Job Vacancy Details, get the drop-down/select lists
            // and return the view to the user.
            else
            {
                JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
                jobApplicationModelObject = jobApplicationApplicationLogicObject.GetJobVacancyDetailsByJobVacancyID(jobApplicationModelObject);

                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobApplicationModelObject.YearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobApplicationModelObject.AcademicEducationQualificationLevelList =
                    requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobApplicationModelObject.SalaryRangeList = salaryRange.GetSalaryRangeList();

                Console.WriteLine("Job Application not created");

                return View(jobApplicationModelObject);
            }
        }

        /// <summary>
        /// Controller Action Method <c>ListShortlistedJobApplicationsByJobVacancyID</c> retrives the shortlisted Job Application for a 
        /// Job Vacancy (by the respective Job Vacancy's ID.
        /// </summary>
        public async Task<IActionResult> ListShortlistedJobApplicationsByJobVacancyID(int JobVacancyID)
        {

            List<JobApplicationModel> shortListedJobApplicationsList = new List<JobApplicationModel>();

            JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
            shortListedJobApplicationsList = jobApplicationApplicationLogicObject.GetShortListedJobApplicationByJobVacancyID(JobVacancyID);

            return View(shortListedJobApplicationsList);
        }
    }
}

Views/JobApplication/CreateJobApplication.cshtml
@model RecruitmentSystemWebApplication.Models.JobApplicationModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Apply for Job Vacancy";
}
<h1>@ViewData["Title"]</h1>
<hr />

<body>
    <h4 class="text-center fw-bolder">Create Job Application</h4>
    @if (Model.JobApplicationCreationAlertID == 1)
    {
        <div class="alert alert-success">
            @Model.SuccessfulJobAppplicationCreationMessage
        </div>
    }

    @if (Model.JobApplicationCreationAlertID == 2)
    {
        <div class="alert alert-danger">
            @Model.UnsuccessfulJobAppplicationCreationMessage
        </div>
    }

    @if (Model.JobApplicationAlreadyExistsState == true)
    {
        <div class="alert alert-danger">
            @Model.JobApplicationAlreadyExistsMessage
        </div>
    }

    <div class="text-center fw-bolder">Company Details</div>

    <div class="row">
        <img src="data:image/png;base64,@Model.CompanyLogoFileBytesToBase64" class="img-thumbnail img-fluid" style="display:block; margin-left:auto; margin-right:auto; max-width:20%; height:auto" alt="Company Logo">
        <div class="form-group row">
            <label asp-for="CompanyName" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="CompanyName" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="CompanyIndustryName" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="CompanyIndustryName" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="CompanySizeRange" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="CompanySizeRange" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="CompanyContactEmailAddress" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="CompanyContactEmailAddress" class="form-control-plaintext  col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="CompanyMainOfficeTownLocation" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="CompanyMainOfficeTownLocation" class="form-control-plaintext col-sm">
        </div>
    </div>
    <hr />

    <div class="text-center fw-bolder mt-3">Job Vacancy Details</div>

    <div class="row">
        <div class="form-group row">
            <label asp-for="JobVacancyTitle" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="JobVacancyTitle" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="JobVacancyLocation" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="JobVacancyLocation" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="JobVacancyRequiredAcademicEducationLevel" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="JobVacancyRequiredAcademicEducationLevel" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="JobVacancyRequiredYearsOfExperience" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="JobVacancyRequiredYearsOfExperience" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="JobVacancyOfferedSalaryRange" class="label fw-bold col-sm"></label>
            <input type="text" readonly asp-for="JobVacancyOfferedSalaryRange" class="form-control-plaintext col-sm">
        </div>

        <div class="form-group row">
            <label asp-for="JobVacancyDescription" class="label fw-bold col-sm"></label>
            <textarea asp-for="JobVacancyDescription" readonly class="form-control col-sm" rows="10"></textarea>
        </div>

    </div>
    <hr />

    <div class="text-center fw-bolder mt-3">Input Your Job Application Details</div>

    <div class="row">
        <form controller="JobApplication" asp-action="CreateJobApplication" enctype="multipart/form-data" method="post" novalidate>
            <div asp-validation-summary="All" class="text-danger"></div>

            <!--Required Academic Qualification Level-->
            <div class="form-group row mt-3">
                <label asp-for="PossessedAcademicEducationQualificationLevelID" class="form-label fw-bold col-sm"></label>
                <select asp-for="PossessedAcademicEducationQualificationLevelID" asp-items="@(new SelectList(Model.AcademicEducationQualificationLevelList, "AcademicEducationQualificationLevelID", "AcademicEducationQualificationLevelName"))" class="form-control col-sm"></select>
                <input type="hidden" asp-for="PossessedAcademicEducationQualificationLevelID" />
                <span asp-validation-for="PossessedAcademicEducationQualificationLevelID" class="text-danger col-sm"></span>
            </div>

            <!--Required Job Experience-->
            <div class="form-group row mt-3">
                <label asp-for="PossessedYearsOfWorkingExperienceRangeID" class="form-label fw-bold col-sm"></label>
                <select asp-for="PossessedYearsOfWorkingExperienceRangeID" asp-items="@(new SelectList(Model.YearsOfWorkingExperienceList, "YearsOfExperienceID", "YearsOfExperienceRangeValue"))" class="form-control col-sm"></select>
                <input type="hidden" asp-for="PossessedYearsOfWorkingExperienceRangeID" />
                <span asp-validation-for="PossessedYearsOfWorkingExperienceRangeID" class="text-danger col-sm"></span>
            </div>

            <!--Offered Salary Range-->
            <div class="form-group row mt-3">
                <label asp-for="PreferredSalaryRangeID" class="form-label fw-bold col-sm"></label>
                <select asp-for="PreferredSalaryRangeID" asp-items="@(new SelectList(Model.SalaryRangeList, "SalaryRangeID", "SalaryRangeValue"))" class="form-control col-sm"></select>
                <input type="hidden" asp-for="PreferredSalaryRangeID" />
                <span asp-validation-for="PreferredSalaryRangeID" class="text-danger col-sm"></span>
            </div>

            <!--CV File-->
            <div class="form-group row mt-3">
                <label asp-for="CVFile" class="form-label fw-bold col-sm"></label>
                <input asp-for="CVFile" class="form-control col-sm" accept=".pdf" />
                <span asp-validation-for="CVFile" class="text-danger col-sm"></span>
            </div>

            <!--Covering Letter-->
            <div class="form-group row mt-3">
                <label asp-for="JobApplicationCoveringLetter" class="form-label fw-bold col-sm"></label>
                <textarea asp-for="JobApplicationCoveringLetter" placeholder="Enter Job Application Covering Letter" class="form-control col-sm" rows="10"></textarea>
                <span asp-validation-for="JobApplicationCoveringLetter" class="text-danger col-sm"></span>
            </div>

            <input type="hidden" asp-for="JobVacancyID" />
            <input type="hidden" asp-for="JobseekerUsername" />


            <div class="form-group text-center  mt-4">
                <input type="submit" value="Submit Job Application" class="btn btn-primary fw-bold" />
            </div>

        </form>
    </div>
</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/JobApplication/ListShortlistedJobApplicationsByJobVacancyID.cshtml
@model IEnumerable<RecruitmentSystemWebApplication.Models.JobApplicationModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewData["Title"] = "View Shortlisted Job Applications";
}
<h1>@ViewData["Title"]</h1>
<hr />

<body>
    <h4 class="text-center fw-bolder">Job Applications</h4>
    <!-- If Model (list of Job Applications By Job Vacancy) is empty, display message -->
    @if (!Model.Any())
    {
        <div class="text-center fw-bolder text-danger">No Shortlisted Job Applications for the selected Job Vacancy Exist</div>
    }

    else
    {
        @foreach (var jobApplication in Model)
        {
            <div class="text-center fw-bolder">Job Vacancy Details</div>

            <div class="row">
                <div class="form-group row">
                    <label asp-for="@jobApplication.JobseekerName" class="label fw-bold col-sm"></label>
                    <input type="text" readonly asp-for="@jobApplication.JobseekerName" class="form-control-plaintext col-sm">
                </div>

                <div class="form-group row">
                    <label asp-for="@jobApplication.JobseekerSurname" class="label fw-bold col-sm"></label>
                    <input type="text" readonly asp-for="@jobApplication.JobseekerSurname" class="form-control-plaintext col-sm">
                </div>

                <div class="form-group row">
                    <label asp-for="@jobApplication.JobseekerContactEmailAddress" class="label fw-bold col-sm"></label>
                    <input type="text" readonly asp-for="@jobApplication.JobseekerContactEmailAddress" class="form-control-plaintext col-sm">
                </div>

                <div class="form-group row">
                    <label asp-for="@jobApplication.JobApplicationCoveringLetter" class="label fw-bold col-sm"></label>
                    <textarea asp-for="@jobApplication.JobApplicationCoveringLetter" readonly class="form-control col-sm" rows="10"></textarea>

                </div>

                <div class="form-group text-center mt-4">
                    <form asp-controller="FileDownloader" asp-action="DownloadCVFile" method="post">
                        <input type="hidden" id="JobApplicationID" name="JobApplicationID" value="@jobApplication.JobApplicationID" />
                        <input type="submit" value="Download CV" class="btn btn-primary fw-bold" />
                    </form>
                </div>

            </div>
            <hr />
        }
    }

</body>