Controllers/JobApplicationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;
using RecruitmentSystemWebApplication.DataAccessLayer.DropDownLists;
using RecruitmentSystemWebApplication.Models;

namespace RecruitmentSystemWebApplication.Controllers
{
    /// <summary>
    /// Class <c>JobApplicationController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for Job Application functionalities.
    /// </summary>
    public class JobApplicationController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public JobApplicationController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Class <c>CreateJobApplication</c> is the controller action method which gets the details of a job vacancy and returns the
        /// CreateJobApplication View. It uses the JobApplicationApplicationLogic class to retrive the Job Vacancy Details.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> CreateJobApplication(int JobVacancyID)
        {
            JobApplicationModel jobApplicationModelObject = new JobApplicationModel();
            jobApplicationModelObject.JobVacancyID = JobVacancyID;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobApplicationModelObject.JobseekerUsername = user.UserName;

            // Get Job Vacancy Details using the Application Logic Layer.
            JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
            jobApplicationModelObject = jobApplicationApplicationLogicObject.GetJobVacancyDetailsByJobVacancyID(jobApplicationModelObject);

            // Populate the View's Dropdown Menu/ Select lists
            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobApplicationModelObject.YearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobApplicationModelObject.AcademicEducationQualificationLevelList =
                requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

            SalaryRange salaryRange = new SalaryRange();
            jobApplicationModelObject.SalaryRangeList = salaryRange.GetSalaryRangeList();

            return View(jobApplicationModelObject);
        }

        /// <summary>
        /// Controller Action Post Method <c>CreateJobApplication</c> is the action method which responsible of creating the job application
        /// after the user submits the Create Job Applicaiton form from the respective view.
        /// It uses the JobApplicationApplicationLogic class to create the Job Application.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CreateJobApplication(JobApplicationModel jobApplicationModelObject)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobApplicationModelObject.JobseekerUsername = user.UserName;

            // If server-side validation passes, call the Application Logic Layer to create the Job Application.
            if (ModelState.IsValid)
            {
                // Create Job Application
                JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
                jobApplicationModelObject = jobApplicationApplicationLogicObject.CreateJobApplicationApplicationLogic(jobApplicationModelObject);

                // Populate Job Application Model Object with related Job Vacancy Details
                jobApplicationModelObject = jobApplicationApplicationLogicObject.GetJobVacancyDetailsByJobVacancyID(jobApplicationModelObject);

                // Populate Dropdown lists
                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobApplicationModelObject.YearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobApplicationModelObject.AcademicEducationQualificationLevelList =
                    requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobApplicationModelObject.SalaryRangeList = salaryRange.GetSalaryRangeList();

                Console.WriteLine("Job Application created");

                // return View with the Job Application Model Object
                return View(jobApplicationModelObject);
            }

            // Else (hence server-side validation on the model object does not pass), get the Job Vacancy Details, get the drop-down/select lists
            // and return the view to the user.
            else
            {
                JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
                jobApplicationModelObject = jobApplicationApplicationLogicObject.GetJobVacancyDetailsByJobVacancyID(jobApplicationModelObject);

                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobApplicationModelObject.YearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobApplicationModelObject.AcademicEducationQualificationLevelList =
                    requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobApplicationModelObject.SalaryRangeList = salaryRange.GetSalaryRangeList();

                Console.WriteLine("Job Application not created");

                return View(jobApplicationModelObject);
            }
        }

        /// <summary>
        /// Controller Action Method <c>ListShortlistedJobApplicationsByJobVacancyID</c> retrives the shortlisted Job Application for a 
        /// Job Vacancy (by the respective Job Vacancy's ID.
        /// </summary>
        public async Task<IActionResult> ListShortlistedJobApplicationsByJobVacancyID(int JobVacancyID)
        {

            List<JobApplicationModel> shortListedJobApplicationsList = new List<JobApplicationModel>();

            JobApplicationApplicationLogic jobApplicationApplicationLogicObject = new JobApplicationApplicationLogic();
            shortListedJobApplicationsList = jobApplicationApplicationLogicObject.GetShortListedJobApplicationByJobVacancyID(JobVacancyID);

            return View(shortListedJobApplicationsList);
        }
    }
}

Controllers/JobVacancyController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.Models;
using RecruitmentSystemWebApplication.DataAccessLayer.DropDownLists;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;

namespace RecruitmentSystemWebApplication.Controllers
{

    /// <summary>
    /// Class <c>JobVacancyController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for Job Vacancy functionalities.
    /// </summary>

    public class JobVacancyController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;


        public JobVacancyController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Controller HTTP Get action method <c>CreateJobVacancy</c> is the controller action method which returns the CreateJobVacancy View
        /// to the user.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> CreateJobVacancy()
        {
            
            JobVacancyModel jobVacancyModel = new JobVacancyModel();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            jobVacancyModel.RecruiterUsername = user.UserName;

            // Populate Drop-Down Menus / Select List for the View
            Town town = new Town();
            jobVacancyModel.townList = town.GetTownList();

            EmploymentBasisType employmentBasisType = new EmploymentBasisType();
            jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobVacancyModel.requiredAcademicEducationQualificationLevelList = requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

            SalaryRange salaryRange = new SalaryRange();
            jobVacancyModel.offeredSalaryRangeList = salaryRange.GetSalaryRangeList();

            JobSpecialization jobSpecialization = new JobSpecialization();
            jobVacancyModel.jobSpecializationList = jobSpecialization.GetJobSpecializationList();

            // Return View with the model to the user
            return View(jobVacancyModel);
        }

        /// <summary>
        /// Controller HTTP Post action method <c>CreateJobVacancy</c> is the controller action method is responsible of handling the UI
        /// logic to create a Job Vacancy after the user submits the respective form from the View.
        /// This action method uses the Applicaiton Logic Layer, which in turn is responsible of calling the Data Access Layer to create 
        /// the job vacancy in the database.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CreateJobVacancy(JobVacancyModel jobVacancyModel)
        {
            // Get Username from the HTTP Context (Security Properties) and set it as the model's username attribute.
            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobVacancyModel.RecruiterUsername = user.UserName;

            // If server-side validation on the model object passes proceed in calling the application logic layer class and method
            // responsible of creating a Job Vacancy, and return the view to the user.
            if (ModelState.IsValid)
            {
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                jobVacancyModel = jobVacancyApplicationLogicObject.CreateJobVacancyApplicationLogic(jobVacancyModel);

                // Populate the model with the lists to be used in the View's Drop-down menus/select lists.
                Town town = new Town();
                jobVacancyModel.townList = town.GetTownList();

                EmploymentBasisType employmentBasisType = new EmploymentBasisType();
                jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobVacancyModel.requiredAcademicEducationQualificationLevelList = requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobVacancyModel.offeredSalaryRangeList = salaryRange.GetSalaryRangeList();

                JobSpecialization jobSpecialization = new JobSpecialization();
                jobVacancyModel.jobSpecializationList = jobSpecialization.GetJobSpecializationList();

                return View(jobVacancyModel);
            }

            // Else (hence server-side validation on the model object did not pass) return the view to the user.
            else
            {
                return View(jobVacancyModel);
            }

        }

        /// <summary>
        /// Controller HTTP Get action method <c>ListJobVacancies</c> is the controller action method is responsible of handling the UI
        /// logic to retrieve a list of Job Vacancies. This controller action method calls different application logic layer methods,
        /// depending on the current user's role.
        /// If the current user's role is Recruiter, then it calls the application logic layer method which retrieves all active (not
        /// deleted/deactivated job vacancies) for his/her company.
        /// If the current user does not have the Recruiter role (hence he/she is a signed in jobseeker or unauthenticated user), a list of
        /// all active job vacancies is retrieved. This is achieved by calling the application logic layer method responsible of retrieving
        /// a list of all active job vacancies.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> ListJobVacancies()
        {
            // If current user has the Recruiter role assigned, retrieve all job vacancies by company.
            // Since a recruiter is related to a single company and vice-versa, the recruiter username is passed onto the logic layer method,
            // responsible of retrieving all active job vacancies by a company.
            if (HttpContext.User.IsInRole("Recruiter"))
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                string RecruiterUsername = user.UserName;
                
                List<JobVacancyModel> jobVacancyList = new List<JobVacancyModel>();
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                
                jobVacancyList = jobVacancyApplicationLogicObject.GetAllJobVacanciesApplicationLogicByCompany(RecruiterUsername);
                return View(jobVacancyList);
            }

            // Else, (hence user is either not signed in or signed in as a jobseeker, return view with all active job vacancies
            else
            {
                List<JobVacancyModel> jobVacancyList = new List<JobVacancyModel>();
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                jobVacancyList = jobVacancyApplicationLogicObject.GetAllJobVacanciesApplicationLogic(jobVacancyList);
                return View(jobVacancyList);
            }
        }

        /// <summary>
        /// Controller <c>ManageJobVacancy</c> handles the UI logic of the Manage Job Vacancy functionality. It retrieves the Job Vacancy
        /// details of the submitted Job Vacancy ID from a view, and returns the ManageJobVacancy view populated with the Job Vacancy details
        /// and several options (including Delete Job Vacancy and View Shortlisted Job Applications) for it.
        /// </summary>
        public async Task<IActionResult> ManageJobVacancy(int JobVacancyID)
        {
            int jobVacancyID = JobVacancyID;
            Console.Write(jobVacancyID.ToString());
            JobVacancyModel jobVacancyModel = new JobVacancyModel();

            JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
            jobVacancyModel = jobVacancyApplicationLogicObject.GetJobVacancyByJobVacancyIDApplicationLogic(JobVacancyID);

            // Populate Job vacancy model with lists to be used with drop down menus in the view. This is done if the recruiter user
            // opts to update the job vacancy (NOTE: Update a Job Vacancy functionality not implemented in its entirety).
            Town town = new Town();
            jobVacancyModel.townList = town.GetTownList();

            EmploymentBasisType employmentBasisType = new EmploymentBasisType();
            jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobVacancyModel.requiredAcademicEducationQualificationLevelList =

Views/JobVacancy/ListJobVacancies.cshtml
@model IEnumerable<RecruitmentSystemWebApplication.Models.JobVacancyModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (User.IsInRole("Recruiter"))
{
    ViewData["Title"] = "Manage Your Company's Job Vacancies";
}

else
{
    ViewData["Title"] = "View Job Vacancies";
}

<h1>@ViewData["Title"]</h1>
<hr />

<body>

    @if (User.IsInRole("Recruiter"))
    {
        <h4 class="text-center fw-bolder"> Create A New Job Vacancy </h4>

        <div class="row mt-4">
            <div class="col text-center">
                <a asp-area="" asp-controller="JobVacancy" asp-action="CreateJobVacancy" class="btn btn-primary fw-bold">Create Job Vacancy</a>
            </div>
        </div>

        <hr />
    }

    @if (User.IsInRole("Recruiter"))
    {
        <h4 class="text-center fw-bolder">Your Company's Current Job Vacancies</h4>
    }

    else
    {
        <h4 class="text-center fw-bolder">Job Vacancies</h4>
    }

    <!-- If Model (list of Job Vacancies) is empty, display message -->
    @if (!Model.Any())
    {
        <div class="text-center fw-bolder text-danger">No Job Vacancies Exist</div>
    }

    // <!-- Else (Model contains job vacancies), display each job vacancy in a Bootstrap card and display different buttons with forms depending on the user's role -->
    else
    {
        <div class="row">

            @foreach (var jobVacancy in Model)
            {
                <div class="col">

                    <!-- Bootstrap 5 Cards Reference: https://getbootstrap.com/docs/5.0/components/card/ & https://getbootstrap.com/docs/5.0/helpers/stretched-link/ -->
                    <div class="card" style="width:18rem; height:auto">
                        <div class="card-title text-center">
                            <h5>@jobVacancy.JobVacancyTitle </h5>
                            <!-- Display from base64 encoded string to .png image Reference: https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html -->
                            <img src="data:image/png;base64,@jobVacancy.CompanyLogoFileBytesToBase64" class="img-thumbnail img-fluid" siz alt="Company Logo">
                        </div>
                        <div class="card-body">
                            <div class="card-text fs-6"> @jobVacancy.CompanyName</div>
                            <div class="card-text fs-6"> @jobVacancy.OfferedSalaryRangeValue </div>
                            <div class="card-text fs-6"> @jobVacancy.JobVacancyLocationName </div>
                            <div class="card-text fs-6"> @jobVacancy.JobVacancyID </div>
                        </div>
                        <div class="card-footer text-center">

                            
                            @if (User.IsInRole("Recruiter"))
                            {
                                <form asp-controller="JobVacancy" asp-action="ManageJobVacancy" method="post">
                                    <!-- Get Job Vacancy ID to be submitted through form -->
                                    <input type="hidden" id="jobVacancyID" name="jobVacancyID" value="@jobVacancy.JobVacancyID" />
                                    <input type="submit" value="Manage Job Vacancy" class="btn btn-primary fw-bold" />
                                </form>
                            }

                            else if (User.IsInRole("Jobseeker"))
                            {
                                <form asp-controller="JobApplication" asp-action="CreateJobApplication" method="get">
                                    <input type="hidden" id="jobVacancyID" name="jobVacancyID" value="@jobVacancy.JobVacancyID" />
                                    <input type="submit" value="Apply for Job Vacancy" class="btn btn-primary fw-bold" formmethod="get" />
                                </form>
                            }

                            else
                            {
                                <form asp-controller="JobVacancy" asp-action="ViewJobVacancy" method="post">
                                    <input type="hidden" id="jobVacancyID" name="jobVacancyID" value="@jobVacancy.JobVacancyID" />
                                    <input type="submit" value="View Job Vacancy" class="btn btn-primary fw-bold" />
                                </form>
                            }

                        </div>
                    </div>
                </div>
            }
        </div>
    }
</body>

Views/JobVacancy/ManageJobVacancy.cshtml
@model RecruitmentSystemWebApplication.Models.JobVacancyModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@{
    ViewData["Title"] = "Manage Job Vacancy";
}
<h1>@ViewData["Title"]</h1>
<hr />

<body>
    <h4 class="text-center fw-bolder">Manage Job Vacancy</h4>

    @if (Model.JobVacancyUpdateAlertID == 1)
    {
        <div class="alert alert-success">
            @Model.SuccessfulJobVacancyUpdateMessage
        </div>
    }

    @if (Model.JobVacancyUpdateAlertID == 2)
    {
        <div class="alert alert-danger">
            @Model.UnsuccessfulJobVacancyUpdateMessage
        </div>
    }

    @if (Model.JobVacancyDeleteAlertID == 1)
    {
        <div class="alert alert-success">
            @Model.SuccessfulJobVacancyDeleteMessage
        </div>
    }

    @if (Model.JobVacancyDeleteAlertID == 2)
    {
        <div class="alert alert-danger">
            @Model.UnsuccessfulJobVacancyDeleteMessage
        </div>
    }

    @if (Model.JobVacancyDeleteAlertID == 0)
    {
        <div class="row">
            <form asp-action="UpdateJobVacancy" enctype="multipart/form-data" novalidate>
                <div asp-validation-summary="All" class="text-danger"></div>

                <!-- Bootstrap horizontal reference https://www.w3schools.com/bootstrap5/bootstrap_grid_stacked_to_hor.php-->
                <div class="form-group row mt-3">

                    <label asp-for="JobVacancyTitle" class="form-label fw-bold col-sm"></label>
                    <input asp-for="JobVacancyTitle" placeholder="Enter Job Vacancy Title" class="form-control col-sm" />
                    <span asp-validation-for="JobVacancyTitle" class="text-danger col-sm"></span>
                </div>

                <!--Job Specialization-->

                <div class="form-group row mt-3">
                    <label asp-for="JobSpecializationID" class="form-label fw-bold col-sm"></label>
                    <select asp-for="JobSpecializationID" asp-items="@(new SelectList(Model.jobSpecializationList, "JobSpecializationID", "JobSpecializationName"))" class="form-control col-sm"></select>
                    <input type="hidden" asp-for="JobSpecializationID" />
                    <span asp-validation-for="JobSpecializationID" class="text-danger col-sm"></span>
                </div>

                <!--Town-->
                <div class="form-group row mt-3">
                    <label asp-for="JobVacancyLocationID" class="form-label fw-bold col-sm"></label>
                    <select asp-for="JobVacancyLocationID" asp-items="@(new SelectList(Model.townList, "TownID", "TownName"))" class="form-control col-sm"></select>
                    <input type="hidden" asp-for="JobVacancyLocationID" />
                    <span asp-validation-for="JobVacancyLocationID" class="text-danger col-sm"></span>
                </div>

                <!--Employment Basis Type-->
                <div class="form-group row mt-3">
                    <label asp-for="EmploymentBasisTypeID" class="form-label fw-bold col-sm"></label>
                    <select asp-for="EmploymentBasisTypeID" asp-items="@(new SelectList(Model.employmentBasisTypeList, "EmploymentBasisTypeID", "EmploymentBasisTypeName"))" class="form-control col-sm"></select>
                    <input type="hidden" asp-for="EmploymentBasisTypeID" />
                    <span asp-validation-for="EmploymentBasisTypeID" class="text-danger col-sm"></span>
                </div>

                <!--Required Academic Qualification Level-->
                <div class="form-group row mt-3">
                    <label asp-for="RequiredAcademicEducationQualificationLevelID" class="form-label fw-bold col-sm"></label>
                    <select asp-for="RequiredAcademicEducationQualificationLevelID" asp-items="@(new SelectList(Model.requiredAcademicEducationQualificationLevelList, "AcademicEducationQualificationLevelID", "AcademicEducationQualificationLevelName"))" class="form-control col-sm"></select>
                    <input type="hidden" asp-for="RequiredAcademicEducationQualificationLevelID" />
                    <span asp-validation-for="RequiredAcademicEducationQualificationLevelID" class="text-danger col-sm"></span>
                </div>

                <!--Required Job Experience-->
                <div class="form-group row mt-3">
                    <label asp-for="RequiredYearsOfWorkingExperienceRangeID" class="form-label fw-bold col-sm"></label>
                    <select asp-for="RequiredYearsOfWorkingExperienceRangeID" asp-items="@(new SelectList(Model.requiredYearsOfWorkingExperienceList, "YearsOfExperienceID", "YearsOfExperienceRangeValue"))" class="form-control col-sm"></select>
                    <input type="hidden" asp-for="RequiredYearsOfWorkingExperienceRangeID" />
                    <span asp-validation-for="RequiredYearsOfWorkingExperienceRangeID" class="text-danger col-sm"></span>
                </div>

                <!--Offered Salary Range-->
                <div class="form-group row mt-3">
                    <label asp-for="OfferedSalaryRangeID" class="form-label fw-bold col-sm"></label>
                    <select asp-for="OfferedSalaryRangeID" asp-items="@(new SelectList(Model.offeredSalaryRangeList, "SalaryRangeID", "SalaryRangeValue"))" class="form-control col-sm"></select>
                    <input type="hidden" asp-for="OfferedSalaryRangeID" />
                    <span asp-validation-for="OfferedSalaryRangeID" class="text-danger col-sm"></span>
                </div>

                <div class="form-group row mt-3">
                    <label asp-for="JobVacancyDescription" class="form-label fw-bold col-sm"></label>
                    <textarea asp-for="JobVacancyDescription" placeholder="Enter Job Vacancy Description" class="form-control col-sm"></textarea>
                    <span asp-validation-for="JobVacancyDescription" class="text-danger col-sm"></span>
                </div>
            </form>

            <form asp-action="DeleteJobVacancy" enctype="multipart/form-data" method="post" novalidate>
                <!-- https://getbootstrap.com/docs/5.0/components/buttons/ -->
                <div class="form-group text-center mt-4">
                    <input type="hidden" asp-for="JobVacancyID" />
                    <input type="submit" value="Delete Job Vacancy" class="btn btn-danger fw-bold" />
                </div>
            </form>

        </div>

        <form asp-controller="JobApplication" asp-action="ListShortlistedJobApplicationsByJobVacancyID" enctype="multipart/form-data" method="post" novalidate>
            <div class="form-group text-center">
                <input type="hidden" asp-for="JobVacancyID" />
                <input type="submit" value="View Short Listed Job Application" class="btn btn-primary fw-bold mt-4" />
            </div>
        </form>
    }
</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }