Controllers/CompanyAccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.Models;
//using System.Diagnostics;
//using RecruitmentSystemWebApplication.Controllers;
using Microsoft.AspNetCore.Authorization;
using RecruitmentSystemWebApplication.DataAccessLayer.DropDownLists;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;

namespace RecruitmentSystemWebApplication.Controllers

{

    /// <summary>
    /// Class <c>CompanyAccountController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for the Company Account Management functionality.
    /// </summary>

    // Only signed-in users with the "Recruiter" role can make use of the controller action methods contained in this controller class.
    [Authorize(Roles = "Recruiter")]
    public class CompanyAccountController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public CompanyAccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Method <c>CompanyAccountMainMenu</c> returns the Company Account Main Menu View to a recruiter, to manage his account.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> CompanyAccountMainMenu()
        {
            return View();
        }

        /// <summary>
        /// Http Get Method <c>UpdateCompany</c> returns the Update Company View along with the model.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> UpdateCompany()
        {
            CompanyModel companyModel = new CompanyModel();
            
            // Get the current username.
            var user = await _userManager.GetUserAsync(HttpContext.User);
            companyModel.RecruiterSignInEmailAddress = user.UserName;

            // Populate the required Dropdown Menus / Select Lists for the form in the respective view
            Town town = new Town();
            companyModel.townList = town.GetTownList();

            CompanySize companySize = new CompanySize();
            companyModel.companySizeList = companySize.GetCompanySizeList();

            Industry industry = new Industry();
            companyModel.industryList = industry.GetIndustryList();

            // Call the application logic method which retrieves the company details/record by recruiter username.
            CompanyApplicationLogic companyApplicationLogicObject = new CompanyApplicationLogic(_userManager);
            companyModel = companyApplicationLogicObject.GetCompanyDetailsByRecruiterUsername(companyModel);
            //var state1 = ModelState;

            // Removes validation (in this case client-side validation) for the Company Model when used in the Update Company context.
            ModelState.Remove("RecruiterSignInEmailAddress");
            ModelState.Remove("RecruiterSignInPassword");
            ModelState.Remove("ConfirmPassword");
            
            // ModelState.Remove on the IFormFile does not work.
            ModelState.Remove(nameof(companyModel.CompanyLogoFile));
            //var keys = ModelState.Keys;
            //var state2 = ModelState;

            // Return the UpdateCompanyView with the CompanyModel containing the company details.
            return View(companyModel);
        }

        /// <summary>
        /// Http Post Method <c>UpdateCompany</c> handles the UI logic when the user submits the form in the UpdateCompany View.
        /// It uses the CompanyApplicationLogic to update the company details.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> UpdateCompany(CompanyModel companyModel)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            companyModel.RecruiterSignInEmailAddress = user.UserName;

            // Remove server side validation for the below Model attributes.
            ModelState.Remove("RecruiterSignInEmailAddress");
            ModelState.Remove("RecruiterSignInPassword");
            ModelState.Remove("ConfirmPassword");
            //ModelState.Remove("CompanyLogoFile");

            // ModelState.Remove does not work on IFormFile Model attributes.
            ModelState.Remove(nameof(companyModel.CompanyLogoFile));

            // If server-side validation on the Model containing the inputted values posted from the form passes, call the respective
            // Application Logic method responsible of updating the Company details.
            if (ModelState.IsValid)
            {
                CompanyApplicationLogic companyApplicationLogicObject = new CompanyApplicationLogic(_userManager);
                companyModel = companyApplicationLogicObject.UpdateCompanyLogic(companyModel);

                // Get the respective lists for the respective drop-down menus for the view and return the view.
                Town town = new Town();
                companyModel.townList = town.GetTownList();

                CompanySize companySize = new CompanySize();
                companyModel.companySizeList = companySize.GetCompanySizeList();

                Industry industry = new Industry();
                companyModel.industryList = industry.GetIndustryList();

                return View(companyModel);
            }

            // Else (hence the server-side validation on the model object containing the submitted values from the form did not pass),
            // populate the required lists for the View Drop-down / select lists, return the model with the view and display an error
            // message to the user.
            else
            {
                companyModel.CompanyUpdateAlertID = 2;

                Town town = new Town();
                companyModel.townList = town.GetTownList();

                CompanySize companySize = new CompanySize();
                companyModel.companySizeList = companySize.GetCompanySizeList();

                Industry industry = new Industry();
                companyModel.industryList = industry.GetIndustryList();

                return View(companyModel);
            }
        }
    }
}

Controllers/JobVacancyController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.Models;
using RecruitmentSystemWebApplication.DataAccessLayer.DropDownLists;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;

namespace RecruitmentSystemWebApplication.Controllers
{

    /// <summary>
    /// Class <c>JobVacancyController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for Job Vacancy functionalities.
    /// </summary>

    public class JobVacancyController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;


        public JobVacancyController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Controller HTTP Get action method <c>CreateJobVacancy</c> is the controller action method which returns the CreateJobVacancy View
        /// to the user.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> CreateJobVacancy()
        {
            
            JobVacancyModel jobVacancyModel = new JobVacancyModel();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            jobVacancyModel.RecruiterUsername = user.UserName;

            // Populate Drop-Down Menus / Select List for the View
            Town town = new Town();
            jobVacancyModel.townList = town.GetTownList();

            EmploymentBasisType employmentBasisType = new EmploymentBasisType();
            jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobVacancyModel.requiredAcademicEducationQualificationLevelList = requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

            SalaryRange salaryRange = new SalaryRange();
            jobVacancyModel.offeredSalaryRangeList = salaryRange.GetSalaryRangeList();

            JobSpecialization jobSpecialization = new JobSpecialization();
            jobVacancyModel.jobSpecializationList = jobSpecialization.GetJobSpecializationList();

            // Return View with the model to the user
            return View(jobVacancyModel);
        }

        /// <summary>
        /// Controller HTTP Post action method <c>CreateJobVacancy</c> is the controller action method is responsible of handling the UI
        /// logic to create a Job Vacancy after the user submits the respective form from the View.
        /// This action method uses the Applicaiton Logic Layer, which in turn is responsible of calling the Data Access Layer to create 
        /// the job vacancy in the database.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CreateJobVacancy(JobVacancyModel jobVacancyModel)
        {
            // Get Username from the HTTP Context (Security Properties) and set it as the model's username attribute.
            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobVacancyModel.RecruiterUsername = user.UserName;

            // If server-side validation on the model object passes proceed in calling the application logic layer class and method
            // responsible of creating a Job Vacancy, and return the view to the user.
            if (ModelState.IsValid)
            {
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                jobVacancyModel = jobVacancyApplicationLogicObject.CreateJobVacancyApplicationLogic(jobVacancyModel);

                // Populate the model with the lists to be used in the View's Drop-down menus/select lists.
                Town town = new Town();
                jobVacancyModel.townList = town.GetTownList();

                EmploymentBasisType employmentBasisType = new EmploymentBasisType();
                jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobVacancyModel.requiredAcademicEducationQualificationLevelList = requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobVacancyModel.offeredSalaryRangeList = salaryRange.GetSalaryRangeList();

                JobSpecialization jobSpecialization = new JobSpecialization();
                jobVacancyModel.jobSpecializationList = jobSpecialization.GetJobSpecializationList();

                return View(jobVacancyModel);
            }

            // Else (hence server-side validation on the model object did not pass) return the view to the user.
            else
            {
                return View(jobVacancyModel);
            }

        }

        /// <summary>
        /// Controller HTTP Get action method <c>ListJobVacancies</c> is the controller action method is responsible of handling the UI
        /// logic to retrieve a list of Job Vacancies. This controller action method calls different application logic layer methods,
        /// depending on the current user's role.
        /// If the current user's role is Recruiter, then it calls the application logic layer method which retrieves all active (not
        /// deleted/deactivated job vacancies) for his/her company.
        /// If the current user does not have the Recruiter role (hence he/she is a signed in jobseeker or unauthenticated user), a list of
        /// all active job vacancies is retrieved. This is achieved by calling the application logic layer method responsible of retrieving
        /// a list of all active job vacancies.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> ListJobVacancies()
        {
            // If current user has the Recruiter role assigned, retrieve all job vacancies by company.
            // Since a recruiter is related to a single company and vice-versa, the recruiter username is passed onto the logic layer method,
            // responsible of retrieving all active job vacancies by a company.
            if (HttpContext.User.IsInRole("Recruiter"))
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                string RecruiterUsername = user.UserName;
                
                List<JobVacancyModel> jobVacancyList = new List<JobVacancyModel>();
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                
                jobVacancyList = jobVacancyApplicationLogicObject.GetAllJobVacanciesApplicationLogicByCompany(RecruiterUsername);
                return View(jobVacancyList);
            }

            // Else, (hence user is either not signed in or signed in as a jobseeker, return view with all active job vacancies
            else
            {
                List<JobVacancyModel> jobVacancyList = new List<JobVacancyModel>();
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                jobVacancyList = jobVacancyApplicationLogicObject.GetAllJobVacanciesApplicationLogic(jobVacancyList);
                return View(jobVacancyList);
            }
        }

        /// <summary>
        /// Controller <c>ManageJobVacancy</c> handles the UI logic of the Manage Job Vacancy functionality. It retrieves the Job Vacancy
        /// details of the submitted Job Vacancy ID from a view, and returns the ManageJobVacancy view populated with the Job Vacancy details
        /// and several options (including Delete Job Vacancy and View Shortlisted Job Applications) for it.
        /// </summary>
        public async Task<IActionResult> ManageJobVacancy(int JobVacancyID)
        {
            int jobVacancyID = JobVacancyID;
            Console.Write(jobVacancyID.ToString());
            JobVacancyModel jobVacancyModel = new JobVacancyModel();

            JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
            jobVacancyModel = jobVacancyApplicationLogicObject.GetJobVacancyByJobVacancyIDApplicationLogic(JobVacancyID);

            // Populate Job vacancy model with lists to be used with drop down menus in the view. This is done if the recruiter user
            // opts to update the job vacancy (NOTE: Update a Job Vacancy functionality not implemented in its entirety).
            Town town = new Town();
            jobVacancyModel.townList = town.GetTownList();

            EmploymentBasisType employmentBasisType = new EmploymentBasisType();
            jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobVacancyModel.requiredAcademicEducationQualificationLevelList =

Views/CompanyAccount/CompanyAccountMainMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Manage Company Account";
}
<h1>@ViewData["Title"]</h1>
<hr />

<body>
    <h4 class="text-center fw-bolder">Company Account Main Menu </h4>

    <div class="row mt-4">
        <div class="col text-center">
            <a asp-area="" asp-controller="CompanyAccount" asp-action="UpdateCompany" class="btn btn-primary fw-bold">Update Company</a>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col text-center">
            <a asp-area="" asp-controller="ChangePassword" asp-action="ChangePassword" class="btn btn-primary fw-bold">Change Password</a>
        </div>
    </div>

    <!--<div class="row mt-4">
        <div class="col text-center">
            <a asp-area="" asp-controller="JobVacancy" asp-action="CreateJobVacancy" class="btn btn-primary fw-bold">Create Job Vacancy</a>
        </div>
    </div>-->

    <div class="row mt-4">
        <div class="col text-center">
            <a asp-area="" asp-controller="JobVacancy" asp-action="ListJobVacancies" class="btn btn-primary fw-bold">Manage Your Company's Job Vacancies'</a>
        </div>
    </div>

</body>

Views/CompanyAccount/UpdateCompany.cshtml
@model RecruitmentSystemWebApplication.Models.CompanyModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Update Company";
}
<h1>@ViewData["Title"]</h1>
<hr />

<body>
    <h4 class="text-center fw-bolder">Update Company</h4>

    @if (Model.CompanyUpdateAlertID == 1)
    {
        <div class="alert alert-success">
            @Model.SuccessfulCompanyUpdateMessage
        </div>
    }

    @if (Model.CompanyUpdateAlertID == 2)
    {
        <div class="alert alert-danger">
            @Model.UnsuccessfulCompanyRegistrationMessage
        </div>
    }

    <div class="row">
        <form asp-action="UpdateCompany" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="All" class="text-danger"></div>

            <!-- Bootstrap horizontal reference https://www.w3schools.com/bootstrap5/bootstrap_grid_stacked_to_hor.php-->
            <div class="form-group row mt-3">

                <label asp-for="CompanyName" class="form-label fw-bold col-sm"></label>
                <input asp-for="CompanyName" placeholder="Enter Company Name" class="form-control col-sm" />
                <span asp-validation-for="CompanyName" class="text-danger col-sm"></span>
            </div>

            <!-- https://getbootstrap.com/docs/5.0/forms/overview/ -->
            <!-- aria-describedby Reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility -->
            <div class="form-group row mt-3">
                <label asp-for="CompanyContactEmailAddress" class="col-form-label fw-bold col-sm"></label>
                <input asp-for="CompanyContactEmailAddress" placeholder="Enter Contact Email Address" class="form-control col-sm" aria-describedby="contact-email-help" />
                <span id="contact-email-help" class="form-text col-sm">This Email address will be posted publicly in job vacancies.</span>
                <span asp-validation-for="CompanyContactEmailAddress" class="text-danger"></span>
            </div>

            <!-- https://www.c-sharpcorner.com/article/net-core-5-dropdownlist/ -->
            <div class="form-group row mt-3">
                <label asp-for="IndustryID" class="form-label fw-bold col-sm"></label>
                <select asp-for="IndustryID" asp-items="@(new SelectList(Model.industryList, "IndustryID", "IndustryName"))" class="form-control col-sm"></select>
                <input type="hidden" asp-for="IndustryID" />
                <span asp-validation-for="IndustryID" class="text-danger col-sm"></span>
            </div>

            <div class="form-group row mt-3">
                <label asp-for="TownID" class="form-label fw-bold col-sm"></label>
                <select asp-for="TownID" asp-items="@(new SelectList(Model.townList, "TownID", "TownName"))" class="form-control col-sm"></select>
                <input type="hidden" asp-for="TownID" />
                <span asp-validation-for="TownID" class="text-danger col-sm"></span>
            </div>

            <div class="form-group row mt-3">
                <label asp-for="CompanySizeID" class="form-label fw-bold col-sm"></label>
                <select asp-for="CompanySizeID" asp-items="@(new SelectList(Model.companySizeList, "CompanySizeID", "CompanySizeName"))" class="form-control col-sm"></select>
                <input type="hidden" asp-for="CompanySizeID" />
                <span asp-validation-for="CompanySizeID" class="text-danger col-sm"></span>
            </div>

            <div class="form-group row mt-3">
                <label asp-for="CompanyLogoFile" class="form-label fw-bold col-sm"></label>
                <input asp-for="CompanyLogoFile" class="form-control col-sm" />
                <span asp-validation-for="CompanyLogoFile" class="text-danger col-sm"></span>
            </div>

            <div class="form-group row mt-3">
                <label asp-for="RecruiterSignInEmailAddress" class="col-form-label fw-bold col-sm"></label>
                <input asp-for="RecruiterSignInEmailAddress" placeholder="Enter Sign-In Email Address" class="form-control col-sm" disabled />
                <span asp-validation-for="RecruiterSignInEmailAddress" class="text-danger col-sm"></span>
            </div>

            <!-- https://getbootstrap.com/docs/5.0/components/buttons/ -->
            <div class="form-group text-center mt-4">
                <input type="submit" value="Update Company" class="btn btn-primary fw-bold" />
            </div>

        </form>
    </div>
</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }