Controllers/JobVacancyController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.Models;
using RecruitmentSystemWebApplication.DataAccessLayer.DropDownLists;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;

namespace RecruitmentSystemWebApplication.Controllers
{

    /// <summary>
    /// Class <c>JobVacancyController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for Job Vacancy functionalities.
    /// </summary>

    public class JobVacancyController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;


        public JobVacancyController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        /// <summary>
        /// Controller HTTP Get action method <c>CreateJobVacancy</c> is the controller action method which returns the CreateJobVacancy View
        /// to the user.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> CreateJobVacancy()
        {
            
            JobVacancyModel jobVacancyModel = new JobVacancyModel();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            jobVacancyModel.RecruiterUsername = user.UserName;

            // Populate Drop-Down Menus / Select List for the View
            Town town = new Town();
            jobVacancyModel.townList = town.GetTownList();

            EmploymentBasisType employmentBasisType = new EmploymentBasisType();
            jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobVacancyModel.requiredAcademicEducationQualificationLevelList = requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

            SalaryRange salaryRange = new SalaryRange();
            jobVacancyModel.offeredSalaryRangeList = salaryRange.GetSalaryRangeList();

            JobSpecialization jobSpecialization = new JobSpecialization();
            jobVacancyModel.jobSpecializationList = jobSpecialization.GetJobSpecializationList();

            // Return View with the model to the user
            return View(jobVacancyModel);
        }

        /// <summary>
        /// Controller HTTP Post action method <c>CreateJobVacancy</c> is the controller action method is responsible of handling the UI
        /// logic to create a Job Vacancy after the user submits the respective form from the View.
        /// This action method uses the Applicaiton Logic Layer, which in turn is responsible of calling the Data Access Layer to create 
        /// the job vacancy in the database.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CreateJobVacancy(JobVacancyModel jobVacancyModel)
        {
            // Get Username from the HTTP Context (Security Properties) and set it as the model's username attribute.
            var user = await _userManager.GetUserAsync(HttpContext.User);
            jobVacancyModel.RecruiterUsername = user.UserName;

            // If server-side validation on the model object passes proceed in calling the application logic layer class and method
            // responsible of creating a Job Vacancy, and return the view to the user.
            if (ModelState.IsValid)
            {
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                jobVacancyModel = jobVacancyApplicationLogicObject.CreateJobVacancyApplicationLogic(jobVacancyModel);

                // Populate the model with the lists to be used in the View's Drop-down menus/select lists.
                Town town = new Town();
                jobVacancyModel.townList = town.GetTownList();

                EmploymentBasisType employmentBasisType = new EmploymentBasisType();
                jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

                YearsOfExperience yearsOfExperience = new YearsOfExperience();
                jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

                AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
                jobVacancyModel.requiredAcademicEducationQualificationLevelList = requiredAcademicEducationQualificationLevel.GetAcademicEducationQualificationLevelList();

                SalaryRange salaryRange = new SalaryRange();
                jobVacancyModel.offeredSalaryRangeList = salaryRange.GetSalaryRangeList();

                JobSpecialization jobSpecialization = new JobSpecialization();
                jobVacancyModel.jobSpecializationList = jobSpecialization.GetJobSpecializationList();

                return View(jobVacancyModel);
            }

            // Else (hence server-side validation on the model object did not pass) return the view to the user.
            else
            {
                return View(jobVacancyModel);
            }

        }

        /// <summary>
        /// Controller HTTP Get action method <c>ListJobVacancies</c> is the controller action method is responsible of handling the UI
        /// logic to retrieve a list of Job Vacancies. This controller action method calls different application logic layer methods,
        /// depending on the current user's role.
        /// If the current user's role is Recruiter, then it calls the application logic layer method which retrieves all active (not
        /// deleted/deactivated job vacancies) for his/her company.
        /// If the current user does not have the Recruiter role (hence he/she is a signed in jobseeker or unauthenticated user), a list of
        /// all active job vacancies is retrieved. This is achieved by calling the application logic layer method responsible of retrieving
        /// a list of all active job vacancies.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> ListJobVacancies()
        {
            // If current user has the Recruiter role assigned, retrieve all job vacancies by company.
            // Since a recruiter is related to a single company and vice-versa, the recruiter username is passed onto the logic layer method,
            // responsible of retrieving all active job vacancies by a company.
            if (HttpContext.User.IsInRole("Recruiter"))
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                string RecruiterUsername = user.UserName;
                
                List<JobVacancyModel> jobVacancyList = new List<JobVacancyModel>();
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                
                jobVacancyList = jobVacancyApplicationLogicObject.GetAllJobVacanciesApplicationLogicByCompany(RecruiterUsername);
                return View(jobVacancyList);
            }

            // Else, (hence user is either not signed in or signed in as a jobseeker, return view with all active job vacancies
            else
            {
                List<JobVacancyModel> jobVacancyList = new List<JobVacancyModel>();
                JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
                jobVacancyList = jobVacancyApplicationLogicObject.GetAllJobVacanciesApplicationLogic(jobVacancyList);
                return View(jobVacancyList);
            }
        }

        /// <summary>
        /// Controller <c>ManageJobVacancy</c> handles the UI logic of the Manage Job Vacancy functionality. It retrieves the Job Vacancy
        /// details of the submitted Job Vacancy ID from a view, and returns the ManageJobVacancy view populated with the Job Vacancy details
        /// and several options (including Delete Job Vacancy and View Shortlisted Job Applications) for it.
        /// </summary>
        public async Task<IActionResult> ManageJobVacancy(int JobVacancyID)
        {
            int jobVacancyID = JobVacancyID;
            Console.Write(jobVacancyID.ToString());
            JobVacancyModel jobVacancyModel = new JobVacancyModel();

            JobVacancyApplicationLogic jobVacancyApplicationLogicObject = new JobVacancyApplicationLogic();
            jobVacancyModel = jobVacancyApplicationLogicObject.GetJobVacancyByJobVacancyIDApplicationLogic(JobVacancyID);

            // Populate Job vacancy model with lists to be used with drop down menus in the view. This is done if the recruiter user
            // opts to update the job vacancy (NOTE: Update a Job Vacancy functionality not implemented in its entirety).
            Town town = new Town();
            jobVacancyModel.townList = town.GetTownList();

            EmploymentBasisType employmentBasisType = new EmploymentBasisType();
            jobVacancyModel.employmentBasisTypeList = employmentBasisType.GetEmploymentBasisList();

            YearsOfExperience yearsOfExperience = new YearsOfExperience();
            jobVacancyModel.requiredYearsOfWorkingExperienceList = yearsOfExperience.GetYearsOfExperienceList();

            AcademicEducationQualificationLevel requiredAcademicEducationQualificationLevel = new AcademicEducationQualificationLevel();
            jobVacancyModel.requiredAcademicEducationQualificationLevelList =

Controllers/JobseekerAccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RecruitmentSystemWebApplication.ApplicationLogicLayer;
using RecruitmentSystemWebApplication.Models;

namespace RecruitmentSystemWebApplication.Controllers
{
    /// <summary>
    /// Class <c>JobseekerAccountController</c> is the controller class containing the controller action methods which handle the User
    /// Interface logic required for for the Jobseeker Account Management functionality.
    /// </summary>
    public class JobseekerAccountController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        //private readonly SignInManager<IdentityUser> _signInManager;


        public JobseekerAccountController(UserManager<IdentityUser> userManager)//, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            //_signInManager = signInManager;
        }

        /// <summary>
        /// Controller Action Method <c>JobseekerAccountController</c> returns the RegisterJobseeker View to the user.
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> RegisterJobseeker()
        {
            JobseekerModel jobseekerModel = new JobseekerModel();

            return View(jobseekerModel);
        }

        /// <summary>
        /// Controller Action Method <c>JobseekerAccountController</c> handles the UI logic after the user submits the form in the RegisterJobseeker View.
        /// It uses the Application Logic Layer to register/create the Jobseeker's User Identity in the Identity Database and Jobseeker details record in the
        /// Application Database.
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> RegisterJobseeker(JobseekerModel jobseekerModel)
        {
            JobseekerApplicationLogic jobseekerRegistrationLogicObject = new JobseekerApplicationLogic(_userManager);

            var JobseekerIdentityCreationState = jobseekerRegistrationLogicObject.JobseekerRegistrationLogic(jobseekerModel);

            // If the Jobseeker's User Identity Result indicates failure, populate the ModelState with errors from the IdentityResult (these are displayed to
            // the user in the view and set the respective boolean value to false.
            if (!JobseekerIdentityCreationState.Succeeded)
            {
                foreach (var Error in JobseekerIdentityCreationState.Errors)
                {
                    ModelState.TryAddModelError(Error.Code, Error.Description);
                    jobseekerModel.SuccessfuJobseekerIdentityRegistrationResponse = false;
                }
            }

            // Jobseeker's User Identity Result indicates a successful user account creation, then set the boolean value to true.
            else
            {
                jobseekerModel.SuccessfuJobseekerIdentityRegistrationResponse = true;
            }

            // If both boolean values are true, set the JobseekerRegistrationAlertID to 1 to display a succesful feedback message to the user.
            if ((jobseekerModel.SuccessfuJobseekerIdentityRegistrationResponse == true) && (jobseekerModel.SuccessfulJobseekerRegistrationResponse == true))
            {
                jobseekerModel.JobseekerRegistrationAlertID = 1;
            }

            // Else (hence a boolean value is not true indicating an error or failure) set the JobseekerRegistrationAlert to 2 to display a failure feedback
            // message to the user.
            else
            {
                jobseekerModel.JobseekerRegistrationAlertID = 2;
            }

            return View(jobseekerModel);

        }

        /// <summary>
        /// Controller Action Method <c>JobseekerAccountMainMenu</c> handles the UI logic to return the Jobseeker Account Main Menu to the user.
        /// </summary>
        public async Task<IActionResult> JobseekerAccountMainMenu()
        {
            return View();
        }
    }
}

Views/JobseekerAccount/JobseekerAccountMainMenu.cshtml
@{
    ViewData["Title"] = "Jobseeker Account Main Menu";
}
<h1>@ViewData["Title"]</h1>
<hr />

<body>

    <h4 class="text-center fw-bolder"> Manage Jobseeker Account Menu</h4>

    <div class="row mt-4">
        <div class="col text-center">
            <a asp-area="" asp-controller="ChangePassword" asp-action="ChangePassword" class="btn btn-primary fw-bold">Change Password</a>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col text-center">
            <a asp-area="" asp-controller="JobVacancy" asp-action="ListJobVacancies" class="btn btn-primary fw-bold">View Job Vacancies</a>
        </div>
    </div>

</body>

Views/JobseekerAccount/RegisterJobseeker.cshtml
@model RecruitmentSystemWebApplication.Models.JobseekerModel

@{
    ViewData["Title"] = "Register Jobseeker";
}
<h1>@ViewData["Title"]</h1>

<hr />
<body>
    <h4 class="text-center fw-bolder">Enter Jobseeker Details</h4>

    @if (Model.JobseekerRegistrationAlertID == 1)
    {
        <div class="alert alert-success">
            @Model.SuccessfulJobseekerRegistrationMessage
        </div>
    }

    @if (Model.JobseekerRegistrationAlertID == 2)
    {
        <div class="alert alert-danger">
            @Model.UnsuccessfulJobseekerRegistrationMessage
        </div>
    }

    <div class="row">
        <form asp-controller="JobseekerAccount" asp-action="RegisterJobseeker" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="All" class="text-danger"></div>

            <!-- Bootstrap horizontal reference https://www.w3schools.com/bootstrap5/bootstrap_grid_stacked_to_hor.php-->
            <div class="row form-group mt-3">
                <label asp-for="JobseekerName" class="form-label fw-bold col-sm"></label>
                <input asp-for="JobseekerName" placeholder="Enter Jobseeker Name" class="form-control col-sm" />
                <span asp-validation-for="JobseekerName" class="text-danger col-sm"></span>
            </div>

            <!-- Bootstrap horizontal reference https://www.w3schools.com/bootstrap5/bootstrap_grid_stacked_to_hor.php-->
            <div class="row form-group mt-3">
                <label asp-for="JobseekerSurname" class="form-label fw-bold col-sm"></label>
                <input asp-for="JobseekerSurname" placeholder="Enter Jobseeker Surname" class="form-control col-sm" />
                <span asp-validation-for="JobseekerSurname" class="text-danger col-sm"></span>
            </div>

            <!-- https://getbootstrap.com/docs/5.0/forms/overview/ -->
            <!-- aria-describedby Reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility -->
            <div class="form-group row mt-3">
                <!--<div class="row g-3 align-items-center">-->
                <label asp-for="JobseekerEmailAddress" class="col-form-label fw-bold col-sm"></label>
                <input asp-for="JobseekerEmailAddress" placeholder="Enter Jobseeker Email Address" class="form-control col-sm" aria-describedby="contact-email-help" />
                <span id="contact-email-help" class="form-text col-sm">This Email address will be shown in your job applications and used for sign-in purposes.</span>
                <span asp-validation-for="JobseekerEmailAddress" class="text-danger"></span>
            </div>

            <div class="form-group row mt-3">
                <label asp-for="JobseekerSignInPassword" class="form-label fw-bold col-sm"></label>
                <input asp-for="JobseekerSignInPassword" placeholder="Enter Jobseeker Sign-In Password" class="form-control col-sm" />
                <span asp-validation-for="JobseekerSignInPassword" class="text-danger col-sm"></span>
            </div>

            <div class="form-group row mt-3">
                <label asp-for="ConfirmPassword" class="form-label fw-bold col-sm"></label>
                <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control col-sm" />
                <span asp-validation-for="ConfirmPassword" class="text-danger col-sm"></span>
            </div>

            <!-- https://getbootstrap.com/docs/5.0/components/buttons/ -->
            <div class="form-group text-center mt-4">
                <input type="submit" value="Register Jobseeker" class="btn btn-primary fw-bold" />
            </div>
        </form>
    </div>
</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }